// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerificacionCrediticia.Infrastructure.Persistence;

#nullable disable

namespace VerificacionCrediticia.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VerificacionCrediticia.Core.Entities.DocumentoProcesado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ConfianzaPromedio")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("DatosExtraidosJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMensaje")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaProcesado")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaProcesado")
                        .HasDatabaseName("IX_DocumentosProcesados_FechaProcesado");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("ExpedienteId", "TipoDocumentoId")
                        .HasDatabaseName("IX_DocumentosProcesados_ExpedienteId_TipoDocumentoId");

                    b.ToTable("DocumentosProcesados", (string)null);
                });

            modelBuilder.Entity("VerificacionCrediticia.Core.Entities.Expediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidosSolicitante")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DniSolicitante")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombresSolicitante")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazonSocialEmpresa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RucEmpresa")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("DniSolicitante")
                        .HasDatabaseName("IX_Expedientes_DniSolicitante");

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("IX_Expedientes_FechaCreacion");

                    b.HasIndex("RucEmpresa")
                        .HasDatabaseName("IX_Expedientes_RucEmpresa");

                    b.ToTable("Expedientes", (string)null);
                });

            modelBuilder.Entity("VerificacionCrediticia.Core.Entities.ReglaEvaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Operador")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("Resultado")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("Activa")
                        .HasDatabaseName("IX_ReglasEvaluacion_Activa");

                    b.HasIndex("Orden")
                        .HasDatabaseName("IX_ReglasEvaluacion_Orden");

                    b.ToTable("ReglasEvaluacion", (string)null);
                });

            modelBuilder.Entity("VerificacionCrediticia.Core.Entities.ResultadoEvaluacionPersistido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NivelRiesgo")
                        .HasColumnType("int");

                    b.Property<int>("Recomendacion")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoCompletoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ScoreFinal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId")
                        .IsUnique()
                        .HasDatabaseName("UX_ResultadosEvaluacion_ExpedienteId");

                    b.HasIndex("FechaEvaluacion")
                        .HasDatabaseName("IX_ResultadosEvaluacion_FechaEvaluacion");

                    b.ToTable("ResultadosEvaluacion", (string)null);
                });

            modelBuilder.Entity("VerificacionCrediticia.Core.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("AnalyzerId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UX_TiposDocumento_Codigo");

                    b.HasIndex("Orden")
                        .HasDatabaseName("IX_TiposDocumento_Orden");

                    b.ToTable("TiposDocumento", (string)null);
                });

            modelBuilder.Entity("VerificacionCrediticia.Core.Entities.DocumentoProcesado", b =>
                {
                    b.HasOne("VerificacionCrediticia.Core.Entities.Expediente", "Expediente")
                        .WithMany("Documentos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentosProcesados_Expediente");

                    b.HasOne("VerificacionCrediticia.Core.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("DocumentosProcesados")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentosProcesados_TipoDocumento");

                    b.Navigation("Expediente");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("VerificacionCrediticia.Core.Entities.ResultadoEvaluacionPersistido", b =>
                {
                    b.HasOne("VerificacionCrediticia.Core.Entities.Expediente", "Expediente")
                        .WithOne("ResultadoEvaluacion")
                        .HasForeignKey("VerificacionCrediticia.Core.Entities.ResultadoEvaluacionPersistido", "ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ResultadosEvaluacion_Expediente");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("VerificacionCrediticia.Core.Entities.Expediente", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("ResultadoEvaluacion");
                });

            modelBuilder.Entity("VerificacionCrediticia.Core.Entities.TipoDocumento", b =>
                {
                    b.Navigation("DocumentosProcesados");
                });
#pragma warning restore 612, 618
        }
    }
}
